### PR TITLE
Consumer-app

### PR DESCRIPTION
**Pull request by kennankole**
* Created a simple page with the name of the app and links to the sign up and log in pages.
 * Allowing  a user  to register in the app with full name, email and password
 * Allowing a user to log into the app using email and password.
 * Logged-in users can access the `Categories`  and `Transactions` pages, Can create new `Categories` and `Transaction`
 * Written `tests`

### CODE REVIEW

**Review by HAMMAS-SALEEM — COMMENTED** [review]
# Invalid Submission :red_circle:

invalid-submission

## Hey @kennankole :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow
✔️ Following some requirements

Good job on implementing some of the requirements but I cannot proceed review of your pull request because there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._


## Mandatory Change ⬇️

- [ ] I saw that you have created multiple branches to create your project and because of that I cannot see all your files in this pull request for a valid review 😨 You are supposed to make only one branch from your development branch and in that one branch you need to make all your changes from setup to finish the project 👍 Kindly follow this requirement and submit your project again to make it clear for the next reviewer 😊

**Comment by HAMMAS-SALEEM** [comment]
For now, you can fix it by merging all your feature branches into your add/views branch

**Comment by kennankole** [comment]
> For now, you can fix it by merging all your feature branches into your add/views branch

Hello @HAMMAS-SALEEM 
Thanks for reviewing my code. 

However, I think there is a misunderstanding about the number of branches I have, I only have three branches and all the code for this PR is in the `add/views` branch. 
Therefore, according to your suggestion above, I have already made this fix because all the code for this review is in the `add/views` branch. 

Thank you

**Review by m05e5 — CHANGES_REQUESTED** [review]
Hi @kennankole 
Good job so far. !
There are some issues that you still need to work on to go to the next project but you are almost there!
mario_ladders


## Highlights

- ✔️ Very nice UI
- ✔️ no linters error 

## Required Changes ♻️
* You really did a great job but there are some features you need to improve

- [ ] Hi as part of the requirements, you're supposed to record a video presentation of 5mins max where you showcase your app and some interesting sides of your code
- [ ] as part of the requirements you are supposed to add to your readme file an appropriate credit to [Gregoire Vella on Behance](https://www.behance.net/gregoirevella) the [author of the original design](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=), as required by the [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/)
- [ ] Hi Please as mentioned in the requirements, you are supposed to deploy the app and add the link to your Readme file
- [ ] Great job with the category but as part of the requirements, the category list is supposed to display the total amount of transactions under that category but right now the value displayed is static on `$50` Kindly fix it 
image

- [ ] As part of the requirements, each category should have a list of its transactions and the total amount on top but currently, each category displays all the transactions created without considering the category_id. kindly display transactions par category only
image
you're supposed to be sorting by category id not by user id

- [ ] Please check the comments below 

_I'm sure you can do it just keep it up_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_@m05e5_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by KDlamini** [comment]
Required changes well resolved ✔️

**Pull request merged**
